/* Report Center. Structured data → reportBuilder → reportRenderer → PDF (browser print) / CSV / XLSX.
 * Formal reports: Finalize → Report ID / UUID / version + classification → canonical artifact + SHA-256 → registry →
 * verification URL + QR on the final page. A finalized report is re-rendered from its frozen record (same ID, same hash). */
(function (C) {
  var P = C.ui.page, RB = C.services.reportBuilder, RR = C.services.reportRenderer, X = C.services.exporter, esc = P.esc, I = C.ui.icons;
  var state = { type: 'combined', data: null, report: null, W: null, run: null, registry: [], view: null, cls: 'CONFIDENTIAL', by: '' };
  var RI = C.services.reportIntegrity;

  function runParam() { return new URLSearchParams(location.search).get('run'); }
  function params() { var t = new URLSearchParams(location.search).get('type'); return RB.TYPES.some(function (x) { return x.id === t; }) ? t : 'combined'; }

  function layout() {
    document.getElementById('page').innerHTML =
      '<div class="c6-intro"><h2 class="c6-intro__title">Report Center 報告中心</h2><p class="c6-intro__text">報告由結構化結果資料產生（Report Data Builder → Report Renderer），不是儀表板截圖。PDF 透過瀏覽器列印產生：A4、頁首頁尾、頁碼、跨頁重複表頭，並保留每一筆資料的來源標示。</p></div>' +
      '<div class="c6-grid">' +
      P.card('rt', '1 · 選擇報告類型', '9 種報告 · 目前評估：<span id="r-as"></span>', '<ul class="c6-rtypes" id="types"></ul>' +
        '<div class="c6-row" id="fair-pick" hidden style="margin-top:1rem;gap:.75rem;flex-wrap:wrap;align-items:flex-end"><label class="c6-field" style="min-width:18rem;flex:1"><span class="c6-var__lbl">FAIR 詳細情境（報告中的百分位、分布圖與超越曲線）</span><select class="c6-input" id="fair-run"></select></label>' +
        '<p class="c6-note" style="flex:1 1 18rem;margin:0">情境比較表一律列出每個情境的最新一次模擬；此處只決定哪一筆模擬顯示詳細內容。</p></div>', { span: 'full' }) +
      P.card('rs', '2 · 章節完整度', '● 已就緒　◐ 含 DATA REQUIRED　— 此報告不適用', '<ul class="c6-rsecs" id="secs"></ul><p class="c6-note" id="r-def" style="margin-top:.75rem"></p>', { span: 'full' }) +
      P.card('rf', '3 · 正式報告：分級與定稿', '定稿後產生 Report ID、UUID、版本與 SHA-256，並登錄至 Report Registry', '<div class="c6-row" style="gap:.75rem;flex-wrap:wrap;align-items:flex-end">' +
        '<label class="c6-field" style="min-width:12rem"><span class="c6-var__lbl">Data Classification</span><select class="c6-input" id="cls">' + RI.CLASSIFICATIONS.map(function (c) { return '<option value="' + c.id + '">' + c.id + ' · ' + c.zh + '</option>'; }).join('') + '</select></label>' +
        '<label class="c6-field" style="min-width:12rem;flex:1"><span class="c6-var__lbl">Generated By 產生者</span><input class="c6-input" id="gen-by" placeholder="姓名 / 職稱"></label>' +
        '<button type="button" class="c6-btn c6-btn--primary" id="finalize">定稿並登錄（Finalize）</button></div>' +
        '<p class="c6-note" id="reg-note" style="margin-top:.75rem"></p>', { span: 'full' }) +
      P.card('ra', '4 · 匯出', 'PDF：在列印對話框選擇「另存為 PDF」，紙張 A4，並勾選「背景圖形」', '<div class="c6-ractions">' +
        '<button type="button" class="c6-btn c6-btn--primary" id="pdf">' + I.icon('download') + '列印 / 儲存 PDF</button>' + P.exportButtons() +
        '<span class="c6-note" id="r-status" role="status" aria-live="polite"></span></div>', { span: 'full' }) +
      P.card('rreg', '5 · Report Registry 已定稿報告', '重新下載使用凍結內容，不會產生新的 Report ID；資料更新請建立新版本', '<div id="reg"></div>', { span: 'full' }) +
      P.card('rp', '6 · 預覽', '與 PDF 使用同一份 HTML；列印時另加頁首（CAT.6 · 組織 · 分級）與頁尾（分級 · Report ID · Page X of Y）', '<div id="view-bar"></div><div class="c6-rpreview-wrap" tabindex="0" aria-label="報告預覽（可捲動）"><div class="c6-rpreview" id="preview"></div></div>', { span: 'full' }) +
      '</div>';
    document.getElementById('page').removeAttribute('aria-busy');
  }

  function renderTypes() {
    document.getElementById('types').innerHTML = RB.TYPES.map(function (t, i) {
      return '<li><button type="button" class="c6-rtype" data-type="' + t.id + '" aria-pressed="' + (t.id === state.type) + '"><span class="c6-rtype__n">Report ' + (i + 1) + '</span><span class="c6-rtype__t">' + esc(t.en) + '</span><span class="c6-rtype__z">' + esc(t.zh) + '</span></button></li>';
    }).join('');
  }

  function build() {
    var W = state.W, d = Object.assign({ assessment: W.assessment }, state.data);
    state.report = RB.build(state.type, d, { mode: W.mode, fairRunId: state.run });
    state.report.classification = state.cls; state.report.generatedBy = state.by;
    var r = state.report;
    renderRunPicker();
    document.getElementById('secs').innerHTML = r.sections.map(function (s) {
      var cls = s.status === 'READY' ? 'is-ready' : s.status === 'PARTIAL' ? 'is-partial' : 'is-na';
      var g = s.status === 'READY' ? '●' : s.status === 'PARTIAL' ? '◐' : '—';
      var lbl = s.status === 'READY' ? '已就緒' : s.status === 'PARTIAL' ? '含 DATA REQUIRED' : '不適用';
      return '<li class="' + cls + '"><span class="g" aria-hidden="true">' + g + '</span><span>' + esc(s.title) + '<span class="c6-sr-only">：' + lbl + '</span></span></li>';
    }).join('');
    document.getElementById('r-def').innerHTML = r.defaultsUsed ? P.chip('CAT.6 DEFAULT / ASSUMED VALUE', 'warn') + ' <strong>' + esc(r.defaultSentence) + '</strong> 報告封面、摘要、假設章節與頁尾都會註明。' : P.chip('組織資料', 'ok') + ' 本報告未使用 CAT.6 預設值。';
    showPreview();
    document.getElementById('r-status').textContent = r.title + ' · ' + r.sections.filter(function (s) { return s.status !== 'NOT_APPLICABLE'; }).length + ' 個章節';
  }

  /* The report on screen / to print: the frozen finalized record being viewed, else the live draft. */
  function shown() { return state.view ? RI.reportFromRecord(state.view) : state.report; }
  function showPreview() {
    var v = state.view;
    document.getElementById('view-bar').innerHTML = v
      ? '<div class="c6-callout" style="margin-bottom:.75rem">檢視已定稿報告 <strong>' + esc(v.reportId) + ' v' + esc(v.reportVersion) + '</strong>（' + esc(v.classification) + ' · 內容已凍結，SHA-256 ' + esc(v.sha256.slice(0, 16)) + '…）　<button type="button" class="c6-btn c6-btn--ghost c6-btn--sm" id="back-draft">返回草稿預覽</button></div>'
      : '<div class="c6-callout c6-callout--warn" style="margin-bottom:.75rem"><strong>DRAFT 草稿預覽</strong>：尚未定稿，沒有 Report ID 與 SHA-256。正式文件請按「定稿並登錄」。</div>';
    var b = document.getElementById('back-draft'); if (b) b.addEventListener('click', function () { state.view = null; showPreview(); });
    document.getElementById('preview').innerHTML = RR.render(shown());
    var qp = '?type=' + state.type + (state.run ? '&run=' + encodeURIComponent(state.run) : '') + (v ? '&report=' + encodeURIComponent(v.reportUuid) : '');
    history.replaceState(null, '', qp);
  }
  function statusChip(r) { return P.chip(r.status, r.status === 'ACTIVE' ? 'ok' : r.status === 'REVOKED' ? 'bad' : 'warn'); }
  function renderRegistry() {
    var kind = RI.registryKind();
    document.getElementById('reg-note').innerHTML = (kind === 'SUPABASE' ? P.chip('SUPABASE REGISTRY', 'accent') + ' 登錄紀錄保存在組織的 Supabase 資料庫。' :
      P.chip('LOCAL DEMO REGISTRY', 'warn') + ' 登錄紀錄只保存在此瀏覽器；Verification Page 只能在同一瀏覽器比對，不是獨立驗證（PRODUCTION REQUIREMENT：Supabase Report Registry）。') +
      ' 數位簽章：<strong>NOT SIGNED — REQUIRES BACKEND</strong>；RFC 3161 時戳：<strong>DEMO / TSA NOT CONNECTED</strong>（未設定後端時不會產生任何簽章或時戳）。';
    var rows = state.registry.slice().sort(function (a, b) { return (b.generatedAt || '').localeCompare(a.generatedAt || ''); });
    var type = {}; RB.TYPES.forEach(function (t) { type[t.id] = t.en; });
    document.getElementById('reg').innerHTML = rows.length ? '<div class="c6-table-wrap"><table class="c6-table"><caption class="c6-sr-only">Report Registry</caption><thead><tr><th scope="col">Report ID</th><th scope="col">Ver.</th><th scope="col">Type</th><th scope="col">Classification</th><th scope="col">Generated At</th><th scope="col">By</th><th scope="col">SHA-256</th><th scope="col">Status</th><th scope="col">操作</th></tr></thead><tbody>' +
      rows.map(function (r) {
        var u = esc(r.reportUuid);
        return '<tr><td><strong>' + esc(r.reportId) + '</strong></td><td>' + esc(r.reportVersion) + '</td><td>' + esc(type[r.reportType] || r.reportType) + '</td><td>' + esc(r.classification) + '</td><td>' + esc(r.generatedAtLocal || r.generatedAt) + '</td><td>' + esc(r.generatedBy || '—') + '</td>' +
          '<td><code title="' + esc(r.sha256) + '">' + esc(r.sha256.slice(0, 12)) + '…</code></td><td>' + statusChip(r) + '</td>' +
          '<td class="c6-row" style="gap:.25rem;flex-wrap:wrap"><button type="button" class="c6-btn c6-btn--ghost c6-btn--sm" data-r="view" data-u="' + u + '">檢視</button><button type="button" class="c6-btn c6-btn--ghost c6-btn--sm" data-r="print" data-u="' + u + '">列印 PDF</button>' +
          '<button type="button" class="c6-btn c6-btn--ghost c6-btn--sm" data-r="manifest" data-u="' + u + '">Manifest</button>' +
          (r.status === 'ACTIVE' ? '<button type="button" class="c6-btn c6-btn--ghost c6-btn--sm" data-r="version" data-u="' + u + '">建立新版本</button><button type="button" class="c6-btn c6-btn--ghost c6-btn--sm" data-r="revoke" data-u="' + u + '">撤銷</button>' : '') +
          '<a class="c6-btn c6-btn--ghost c6-btn--sm" href="' + esc(RI.verifyUrl(r)) + '" target="_blank" rel="noopener">驗證頁</a></td></tr>';
      }).join('') + '</tbody></table></div>' : '<div class="c6-empty">尚無已定稿報告。</div>';
  }
  function reloadRegistry() { return RI.list().then(function (l) { state.registry = l; renderRegistry(); }); }
  function finalize(previous) {
    var btn = document.getElementById('finalize'); btn.disabled = true;
    var report = previous ? RB.build(previous.reportType, Object.assign({ assessment: state.W.assessment }, state.data), { mode: state.W.mode, fairRunId: state.run }) : state.report;
    return RI.finalize({ report: report, classification: previous && !state.clsTouched ? previous.classification : state.cls, generatedBy: state.by || (previous && previous.generatedBy) || '', previous: previous || null })
      .then(function (rec) { C.util.dom.toast('已定稿 ' + rec.reportId + ' v' + rec.reportVersion + ' · SHA-256 ' + rec.sha256.slice(0, 12) + '…'); state.view = rec; return reloadRegistry().then(showPreview); })
      .catch(function (e) { C.util.dom.toast('定稿失敗：' + e.message, 'bad'); })
      .then(function () { btn.disabled = false; });
  }
  function onRegistry(e) {
    var b = e.target.closest('[data-r]'); if (!b) return;
    var rec = state.registry.filter(function (r) { return r.reportUuid === b.getAttribute('data-u'); })[0]; if (!rec) return;
    var act = b.getAttribute('data-r');
    if (act === 'view') { state.view = rec; showPreview(); document.getElementById('rp').scrollIntoView({ block: 'start' }); }
    if (act === 'print') { state.view = rec; showPreview(); RR.print(RI.reportFromRecord(rec)); state.W.log('列印已定稿報告 ' + rec.reportId + ' v' + rec.reportVersion, 'CALCULATED'); }
    if (act === 'manifest') C.util.dom.download(rec.reportId + '_v' + rec.reportVersion + '.cat6report.json', rec.canonical, 'application/json');
    if (act === 'version') C.ui.form.confirm('以目前資料建立 ' + rec.reportId + ' 的新版本（v' + RI.nextVersion(rec.reportVersion) + '）？舊版本將標示為 SUPERSEDED。', '建立新版本').then(function (ok) { if (ok) finalize(rec); });
    if (act === 'revoke') C.ui.form.open({ title: '撤銷 ' + rec.reportId + ' v' + rec.reportVersion, subtitle: '撤銷後 Verification Page 顯示 REVOKED；紀錄保留、不可復原。', fields: [{ key: 'reason', label: '撤銷原因', type: 'text', required: true }] })
      .then(function (v) { if (v) return RI.revoke(rec, v.reason).then(function () { if (state.view && state.view.reportUuid === rec.reportUuid) state.view = null; return reloadRegistry().then(showPreview); }); });
  }

  /* Every saved simulation (newest first); the latest run of each scenario is marked. */
  function renderRunPicker() {
    var box = document.getElementById('fair-pick'), runs = (state.data.fairRuns || []).slice().sort(function (a, b) { return (b.at || '').localeCompare(a.at || ''); });
    box.hidden = !(state.report && state.report.hasFair && runs.length);
    if (box.hidden) return;
    var latest = {}; RB.latestPerRisk(state.data).forEach(function (r) { latest[r.id] = true; });
    var name = {}; (state.data.risks || []).forEach(function (r) { name[r.id] = r.scenario; });
    var sel = state.report.fairRunId, F = C.util.format;
    document.getElementById('fair-run').innerHTML = runs.map(function (r) {
      return '<option value="' + esc(r.id) + '"' + (r.id === sel ? ' selected' : '') + '>' + esc((r.riskId || '—') + ' · ' + (name[r.riskId] || '') + ' — ' + r.id + ' · ' + (r.at || '').replace('T', ' ').slice(0, 16) + ' · ' + F.num(r.iterations) + ' 次 · seed ' + r.seed + (latest[r.id] ? ' · 該情境最新' : '')) + '</option>';
    }).join('');
  }
  function exportCSV() {
    var tables = exportTables(), rows = [];
    tables[0].notes.forEach(function (n) { rows.push(['# ' + n]); });
    tables.forEach(function (t) { rows.push([]); rows.push(['## ' + t.name]); X.matrix(t).forEach(function (m) { rows.push(m); }); });
    C.util.dom.download(fileBase() + '.csv', X.toCSV(rows), 'text/csv;charset=utf-8');
  }
  function fileBase() { var v = state.view; return v ? v.reportId + '_v' + v.reportVersion + '_' + v.reportType : 'CAT6_DRAFT_' + state.type + '_' + new Date().toISOString().slice(0, 10); }
  function exportTables() {
    var r = shown(), t = RB.toTables(r), m = RR.metaOf(r);
    t[0].notes = [m.classification + (m.classification === 'PUBLIC' ? '' : ' — CAT.6 CYBERSECURITY'), m.draft ? 'DRAFT — NOT FINALIZED' : 'Report ID ' + m.reportId + ' · v' + m.reportVersion + ' · UUID ' + m.reportUuid + ' · SHA-256 ' + state.view.sha256].concat(t[0].notes);
    t.forEach(function (x) { x.notes = t[0].notes; });
    return t;
  }

  P.boot({ nav: 'reports' }, function (W) {
    state.W = W; state.type = params(); state.run = runParam(); var wantReport = new URLSearchParams(location.search).get('report');
    layout();
    document.getElementById('r-as').textContent = W.assessment ? W.assessment.organization + ' · ' + W.assessment.name : '—';
    renderTypes();
    return Promise.all([W.load(RB.COLLECTIONS), RI.list()]).then(function (res) {
      var d = res[0]; state.data = d; state.registry = res[1];
      state.view = wantReport ? state.registry.filter(function (r) { return r.reportUuid === wantReport; })[0] || null : null;
      renderRegistry();
      build();
      document.getElementById('cls').value = state.cls;
      document.getElementById('cls').addEventListener('change', function (e) { state.cls = e.target.value; state.clsTouched = true; if (!state.view) build(); });
      document.getElementById('gen-by').addEventListener('input', function (e) { state.by = e.target.value.trim(); if (!state.view) { state.report.generatedBy = state.by; showPreview(); } });
      document.getElementById('finalize').addEventListener('click', function () { finalize(null); });
      document.getElementById('reg').addEventListener('click', onRegistry);
      P.notice(document.getElementById('c6-notice'), state.report.defaultsUsed, { edit: 'risk-assessment.html', dataset: '' });
      document.getElementById('types').addEventListener('click', function (e) {
        var b = e.target.closest('[data-type]'); if (!b) return;
        state.type = b.getAttribute('data-type'); state.view = null; renderTypes(); build();
        var nb = document.querySelector('[data-type="' + state.type + '"]'); if (nb) nb.focus();
      });
      document.getElementById('fair-run').addEventListener('change', function (e) { state.run = e.target.value; state.view = null; build(); });
      document.getElementById('pdf').addEventListener('click', function () { var r = shown(); RR.print(r); W.log('產生 PDF 報告：' + r.title + (state.view ? '（' + state.view.reportId + ' v' + state.view.reportVersion + '）' : '（DRAFT）'), 'CALCULATED'); });
      P.bindExport(document.getElementById('ra'), function (kind) {
        if (kind === 'csv') exportCSV(); else X.downloadXLSX(exportTables(), fileBase());
        W.log('匯出 ' + kind.toUpperCase() + ' 報告：' + state.report.title, 'CALCULATED');
      });
    });
  });
})(globalThis.CAT6);
